# Generated by Django 3.2.11 on 2022-01-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20220125_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='subtitulo',
            field=models.CharField(default='Subtitulo', max_length=200, verbose_name='Subtítulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
