# Generated by Django 3.2.11 on 2022-01-25 22:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='subtitulo',
            field=models.CharField(max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='texto',
            field=tinymce.models.HTMLField(verbose_name='Texto'),
        ),
    ]
